### ISSUE TITLE
Create hashes.json

### ISSUE THREAD

**Issue by robvangeloven** [chip-8/chip-8-database#4]
As the title says, the documentation mentions a hashes.json. However there is no such file in the repo?

**Comment by tobiasvl** [comment]
Thanks, this should definitely be prioritized.

Per discussion in #3 I think we settled on SHA-1, so let's hash all available ROMs and upload a first version.

**Comment by zZeck** [comment]
I think I linked you this [list of games and hashes](https://github.com/zZeck/Octo/blob/typescript/docs/Links.txt) in 2019 via email.

It may be easier to make a script to run over the roms again yourself, and output the json, but here it is again in case it's useful.
