### ISSUE TITLE
Standardize JSON schema, with versions

### ISSUE THREAD

**Issue by tobiasvl** [chip-8/chip-8-database#5]
What attributes do we need for games in the database (`programs.json`)?

See #3 and finalize its discussion, so it can finally be merged and serve as an example for good entries. CC @metteo

Could also take a look at https://crates.io/crates/octopt, not necessarily because we need to harmonize these projects of mine, but `octopt` is one of my recent takes on generalizing CHIP-8 metadata (ie. I spun that project off of this and neglected this one, basically).

**Comment by metteo** [comment]
Hi @tobiasvl long time no see 😅

I agree, we should finalize the schema so it's possible to start describing roms.

I tried to check the link you provided but it gives 404.

BTW we could use JSON Schema to formalize the format and also describe what the fields mean.

Versioning is a great idea. Generally JSON parsers are fine when adding new properties. Only changing / removing properties breaks compatibility.

**Comment by tobiasvl** [comment]
Link fixed

**Comment by Timendus** [comment]
I'm working on a proposal for the new schema in #11. I've taken inspiration from #3, from `octopt` and from my other standardization project Chip-8 binary format, merging all those ideas together to get to what I currently think is the best mix.
